export const SELECT_PAYMENT_REQUEST = 'SELECT_PAYMENT_REQUEST';
export const SELECT_PAYMENT_SUCCESS = 'SELECT_PAYMENT_SUCCESS';
export const SELECT_PAYMENT_FAILURE = 'SELECT_PAYMENT_FAILURE';

export const SELECT_PRODUCT_REQUEST = 'SELECT_PRODUCT_REQUEST';
export const SELECT_PRODUCT_SUCCESS = 'SELECT_PRODUCT_SUCCESS';
export const SELECT_PRODUCT_FAILURE = 'SELECT_PRODUCT_FAILURE';
